[tox]
env_list =
    py310-dj42
    py312-dj42
    py310-dj50
    py312-dj50
    py310-dj51
    py313-dj51

[testenv]
package = wheel
wheel_build_env = .pkg
deps =
    pytest
    pytest-django
    pytest-cov
    django-stubs-ext
    inline-snapshot
    inline-snapshot-django
    dj42: django>=4.2,<4.3
    dj50: django>=5.0,<5.1
    dj51: django>=5.1,<5.2
commands =
    pytest tests --ignore=tests/e2e {posargs}
